
receivers:
  otlp:
    protocols:
      grpc: { endpoint: 0.0.0.0:4317 }
      http: { endpoint: 0.0.0.0:4318 }
  prometheus:
    config:
      scrape_configs:
        - job_name: load-generator
          scrape_interval: 15s
          static_configs:
            - targets: ["load-generator:8090"]

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  prometheusremotewrite:
    endpoint: "${PROMETHEUS_REMOTE_WRITE_ENDPOINT}"
  splunk_hec:
    endpoint: "${SPLUNK_HEC_ENDPOINT}"
    token: "${SPLUNK_HEC_TOKEN}"
    source: "banking-app"
    sourcetype: "java-otel"
    index: "${SPLUNK_INDEX}"
    tls: { insecure_skip_verify: true }
  elasticsearch/opensearch:
    endpoints: ["${OPENSEARCH_ENDPOINT}"]
    logs_index: "${OPENSEARCH_LOGS_INDEX}"
  otlphttp/jaeger:
    traces_endpoint: "${JAEGER_TRACES_ENDPOINT}"
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/jaeger, logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus, prometheusremotewrite, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [splunk_hec, elasticsearch/opensearch, logging]
