


receivers:
  otlp:
    protocols:
      grpc: { endpoint: 0.0.0.0:4317 }
      http: { endpoint: 0.0.0.0:4318 }
  prometheus:
    config:
      scrape_configs:
        - job_name: load-generator
          scrape_interval: 15s
          static_configs:
            - targets: ["load-generator:8090"]

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  splunk_hec:
    endpoint: "http://10.235.21.132:8088/services/collector"
    token: "2bc8a6c2-a512-4afe-aebd-bf34dd4a5910"
    source: "banking-app"
    sourcetype: "java-otel"
    index: "main"
    tls: { insecure_skip_verify: true }
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [splunk_hec, logging]
